development:
  adapter: postgis
  encoding: utf8
  reconnect: false
  database: player_stat_development
  pool: 5
  username: arinashmeleva
  host: localhost
  port: 5432


test:
  adapter: postgis
  encoding: utf8
  reconnect: false
  database:  player_stat_test
  pool: 5
  username: arinashmeleva
  host: localhost
  port: 5432